export const UI_TEXT = {
  APP_TITLE: "Đầy Bình",
  FUEL_SECTION_GAS: "Xăng",
  FUEL_SECTION_OTHER: "Dầu hỏa & DO",
  CALCULATOR_TITLE: "Bảng Giá Đổ Đầy Bình",
  CALCULATOR_TITLE_BIKE: "Bảng Giá Đổ Đầy Bình Xe Máy",
  CALCULATOR_TITLE_CAR: "Bảng Giá Đổ Đầy Bình Xe Hơi",
  CALCULATOR_SUBTITLE: "Tìm xe để xem chi phí cho tất cả loại xăng",
  UNIT_VND_PER_LITRE: "VND / Lít",
  UNIT_LITRE: "Lít",
  UNIT_VND: "VND",
  LAST_UPDATED: "Cập nhật",
  COMPARE_TABLE_LABEL: "Bảng So Sánh Chi Phí (Dự Kiến)",
  COMPARE_TABLE_UNIT: "* Đơn vị: VND",
  REFRESH_BUTTON: "Làm mới dữ liệu",
  DATA_SOURCE: "Dữ liệu được cung cấp bởi giaxanghomnay & VNExpress",
  TAB_MOTORCYCLE: "Xe Máy",
  TAB_CAR: "Xe Hơi",
  TABLE_COL_VEHICLE_NAME: "Tên Xe",
  ACTION_DELETE: "Xóa",
  ACTION_DELETE_VEHICLE: "Xoá xe",
  ACTION_ADD_MORE: (count: number) => `Chọn thêm (còn ${count})`,
};
